import React from "react";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Head from "next/head";

const Layout = ({ children, titulo = 'INSSJP - Instituto Nacional de Servicios Sociales para Jubilados y Pensionados' }) => {
  return (
    <>
      <Head>
        <title>{titulo}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <main>{children}</main>
      <Footer />
    </>
  );
};

export default Layout;
