import Head from "next/head";
import { GoPrimitiveDot } from "react-icons/go";
import TituloCeleste from "../../components/Genericos/TituloCeleste";
import BotonVolver from "../../components/Genericos/BotonVolver";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Web INSSJP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Imagen Encabezado */}
      <div className="w-full mt-[120px]">
        <img
          src="https://www.pami.org.ar/imagenes/headers/historia.jpg"
          className="w-full"
        />
      </div>

      {/* Seccion */}
      <div className="pl-[100px] pr-[100px] pt-10 pb-10">
        <div className="pb-10">
          <p className="mb-2">
            El Instituto Nacional de Servicios Sociales para Jubilados y
            Pensionados, más conocido como PAMI fue creado en 1971 con el
            objetivo de <b>brindar asistencia médica integral</b> a las personas
            mayores.
          </p>
          <p className="mb-2">
            PAMI es la obra social más grande de Latinoamérica. Acompañamos a <b>5
            millones</b> de jubilados y sus familiares a cargo, pensionados y
            veteranos de Malvinas.
          </p>
          <p>
            Nuestro <b>Programa de Asistencia Médica Integral</b> incluye prestaciones
            médicas y sociales, porque una vida activa es clave para gozar de
            una buena salud.
          </p>
        </div>
        <div className="pb-8">
          <TituloCeleste texto=" Estamos cerca tuyo, en cada rincón del país, con:" />
          <ul>
            <li>
              <a href="#" class="w-fill flex p-3 pl-3">
                <GoPrimitiveDot />
                <span class="ml-3">
                 <b>Más de 600 Agencias de Atención y 38 Unidades de Gestión
                  Local</b>, donde podés realizar todos tus trámites y recibir una
                  atención personalizada.
                </span>
              </a>
            </li>
            <li>
              <a href="#" class="w-fill flex p-3 pl-3">
                <GoPrimitiveDot />
                <span class="ml-3">
                  Más de 8 mil Médicos de Cabecera y 17 mil prestadores con los
                  que podés atenderte.
                </span>
              </a>
            </li>
            <li>
              <a href="#" class="w-fill flex p-3 pl-3">
                <GoPrimitiveDot />
                <span class="ml-3">
                  Más de 14 mil farmacias adheridas para retirar tus
                  medicamentos con la mejor cobertura.
                </span>
              </a>
            </li>
          </ul>
        </div>
        <BotonVolver />
      </div>
    </div>
  );
}
